spring.application.name=job-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true